apiVersion: batch/v1
kind: CronJob
metadata:
  name: ingestion-service
  namespace: orderflow
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ingestion-service
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
          containers:
            - name: ingestion
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              envFrom:
                - configMapRef:
                    name: ingestion-service-config
              env:
                {{- range $key, $value := .Values.secrets }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      name: ingestion-service-secrets
                      key: {{ $key | lower }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          backoffLimit: {{ .Values.cronJob.backoffLimit }}