apiVersion: v1
kind: ServiceAccount
metadata:
  name: genai-service
  namespace: orderflow
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}