apiVersion: v1
kind: ConfigMap
metadata:
  name: orderflow-config
  namespace: orderflow
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DB_NAME: "orderflow"
  DB_USERNAME: "orderflow_user"
  DB_PORT: "5432"
  QDRANT_PORT: "6333"
  QDRANT_COLLECTION: "devops-docs"
  AWS_REGION: "eu-central-1"
  BEDROCK_EMBEDDING_MODEL: "amazon.titan-embed-text-v1"
  BEDROCK_MODEL_ID: "anthropic.claude-3-sonnet-20240229-v1:0"