replicaCount: 1

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

autoscaling:
  enabled: false

env:
  ENVIRONMENT: development
  LOG_LEVEL: DEBUG