aws_region             = "eu-central-1"
project_name           = "orderflow"
environment            = "dev"
vpc_cidr               = "10.0.0.0/16"
availability_zones     = ["eu-central-1a", "eu-central-1b"]
public_subnet_cidrs    = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs   = ["10.0.10.0/24", "10.0.11.0/24"]
db_instance_class      = "db.t3.micro"
node_instance_type     = "t3.medium"
node_desired_size      = 2
node_min_size          = 1
node_max_size          = 3